workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo


  build_docker_image:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - TAG=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    commands:
      - docker login -u="${QUAY_USERNAME}" -p="${QUAY_PASSWORD}" quay.io
      - docker build -t image .      
      - docker tag image quay.io/ipedrazas/drone-helm:latest
      - docker tag image quay.io/ipedrazas/drone-helm:${TAG}
      - docker push quay.io/ipedrazas/drone-helm
        
services:
  dind:
    image: docker:1.12-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
  
plugin:
  name: drone-helm
  desc: Execute helm to 
  type: deploy
  image: quay.io/ipedrazas/drone-helm
  labels:
    - deploy
    - kubernetes
    - helm